import { BroadcasterBuilder } from '../../src'
import { image } from '../../src/util/loader'

describe('broadcasterBuilder', () => {
  it('デフォルトの設定を変更できる', () => {
    const def = BroadcasterBuilder.getDefault(scene)
    expect(def.location()).toEqual({ x: 0, y: 0 })
    expect(def.speed()).toEqual(1)
    expect(def.asset()).toMatchObject({ path: './image/broadcaster.default.png' })
    expect(def.vars()).not.toBeDefined()
    def.location({ x: 1, y: 2 })
    def.speed(2)
    def.asset(scene.asset.getImageById('default'))
    def.vars('foo')
    expect(def.location()).toEqual({ x: 1, y: 2 })
    expect(def.speed()).toBe(2)
    expect(def.asset()).toMatchObject({ path: './image/default.png' })
    expect(def.vars()).toBe('foo')
    const bb = new BroadcasterBuilder(scene)
    expect(bb.location()).toEqual({ x: 1, y: 2 })
    expect(bb.speed()).toBe(2)
    expect(bb.asset()).toMatchObject({ path: './image/default.png' })
    expect(bb.vars()).toBe('foo')
  })
  it('デフォルトの設定で作成できる', () => {
    const bb = new BroadcasterBuilder(scene)
    expect(bb.speed()).toEqual(1)
    expect(bb.asset().path).toBe('./image/broadcaster.default.png')
    expect(bb.location()).toEqual({ x: 0, y: 0 })
    expect(bb.vars()).not.toBeDefined()
    const broadcaster = bb.build()
    expect(broadcaster.speed).toBe(1)
    expect(broadcaster.view).toBeInstanceOf(g.Sprite)
    expect(((broadcaster.view as g.Sprite).src as g.ImageAsset).path).toBe('./image/broadcaster.default.png')
    expect(broadcaster.view).toMatchObject({ x: 0, y: 0 })
    expect(broadcaster.vars).not.toBeDefined()
  })

  it('カスタム設定で作成できる', () => {
    const bb = new BroadcasterBuilder(scene)
      .speed(2)
      .asset(image(scene, 'image/default.png'))
      .location({ x: 100, y: 200 })
      .vars({ foo: 'bar' })
    expect(bb.speed()).toEqual(2)
    expect(bb.location()).toEqual({ x: 100, y: 200 })
    expect(bb.asset().path).toBe('./image/default.png')
    expect(bb.vars()).toEqual({ foo: 'bar' })
    const broadcaster = bb.build()
    expect(broadcaster.speed).toBe(2)
    expect(broadcaster.view).toBeInstanceOf(g.Sprite)
    expect(((broadcaster.view as g.Sprite).src as g.ImageAsset).path).toBe('./image/default.png')
    expect(broadcaster.view).toMatchObject({ x: 100, y: 200 })
    expect(broadcaster.vars).toEqual({ foo: 'bar' })
  })

  it('不正な値は設定できない', () => {
    const bb = new BroadcasterBuilder(scene)
    expect(() => bb.speed(-1)).toThrow()
    expect(bb.speed()).toBe(1)
  })

  it('varsにundefinedを入れられる', () => {
    const bb = new BroadcasterBuilder(scene)
      .vars('hoge')
      .vars(undefined)
    expect(bb.vars()).not.toBeDefined()
    const broadcaster = bb.build()
    expect(broadcaster.vars).not.toBeDefined()
  })
})
