name: verify

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/cache@v4
        id: cache-restore
        with:
          path: node_modules
          key: dependencies-${{ hashFiles('package-lock.json') }}
      - run: npm ci
        if: steps.cache-restore.outputs.cache-hit != 'true'
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: dependencies-${{ hashFiles('package-lock.json') }}
      - run: npm run lint:check
  build:
    runs-on: ubuntu-latest
    needs:
      - setup
      - lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: dependencies-${{ hashFiles('package-lock.json') }}
      - run: npm run build:image
  test:
    runs-on: ubuntu-latest
    needs:
      - setup
      - lint
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: dependencies-${{ hashFiles('package-lock.json') }}
      - run: npm test
